import { createServer, IncomingMessage, ServerResponse } from 'http';
import { parse } from 'url';
import next from 'next';
import fs from 'fs';
import path from 'path';
import { httpRequestDuration, httpRequestTotal, httpActiveRequests, register } from './src/lib/metrics';

const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();
const IGNORED_PREFIXES = ['/_next/', '/favicon.ico', '/metrics'];

// Common bot/scanner patterns
const BOT_PATTERNS = [
  /\.env/, // Matches .env anywhere (including /.env)
  /\.git/,
  /wp-admin/,
  /wp-login/,
  /phpMyAdmin/,
  /\.php$/,
  /\/admin/, // Added slash for /admin specifically
  /\/config/, // Added slash for /config
  /\.xml$/,
  /\.sql$/,
  /\/backup/, // Added slash for /backup
  /\.zip$/,
];

function isBotPattern(pathname: string): boolean {
  return BOT_PATTERNS.some(pattern => pattern.test(pathname));
}

// Scan app directory for routes (dev mode only)
function scanAppDirectory(baseDir: string, currentDir: string, routes: Set<string>) {
  try {
    // Check if directory exists first
    if (!fs.existsSync(currentDir)) {
      console.warn(`⚠️ Directory not found: ${currentDir}`);
      return;
    }

    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        // Skip special Next.js directories
        if (entry.name.startsWith('_')) continue;
        const fullPath = path.join(currentDir, entry.name);
        scanAppDirectory(baseDir, fullPath, routes);
      } else if (entry.name === 'page.tsx' || entry.name === 'page.js') {
        // Convert file path to route
        const routePath = currentDir
          .replace(baseDir, '')
          .replace(/\\/g, '/') || '/';
        routes.add(routePath);
      }
    }
  } catch (error) {
    console.warn('⚠️ Error scanning directory:', error);
  }
}

// Dynamically load known routes from Next.js build manifest
function loadKnownRoutes(): Set<string> {
  const knownRoutes = new Set<string>(['/']); // Always include root
  if (!dev) {
    try {
      // Read the app-paths-manifest.json generated by Next.js
      const manifestPath = path.join(process.cwd(), '.next/server/app-paths-manifest.json');
      const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
      Object.keys(manifest).forEach(route => {
        knownRoutes.add(route);
      });
      console.log('📋 Loaded routes from manifest:', Array.from(knownRoutes));
    } catch (error) {
      console.warn('⚠️ Could not load app-paths-manifest.json:', error);
    }
  } else {
    // In dev mode, try to find the app directory
    const possiblePaths = [
      path.join(process.cwd(), 'app'),
      path.join(process.cwd(), 'src', 'app'),
    ];
    let appDir: string | null = null;
    for (const p of possiblePaths) {
      if (fs.existsSync(p)) {
        appDir = p;
        break;
      }
    }
    if (appDir) {
      console.log(`📂 Scanning app directory: ${appDir}`);
      scanAppDirectory(appDir, appDir, knownRoutes);
      console.log('📋 Loaded routes from filesystem:', Array.from(knownRoutes));
    } else {
      console.warn('⚠️ Could not find app directory. Using root route only.');
      console.warn('💡 Add your routes manually or ensure app/ or src/app/ exists.');
    }
  }
  return knownRoutes;
}

// Initialize known routes (will be set after app.prepare())
let KNOWN_ROUTES_SET: Set<string>;

function normalizeRoute(pathname: string): string {
  // Check exact match first (static routes like "/about")
  if (KNOWN_ROUTES_SET.has(pathname)) {
    return pathname;
  }

  // Check against dynamic patterns
  for (const knownRoute of KNOWN_ROUTES_SET) {
    if (knownRoute.includes('[')) {
      const pattern = knownRoute
        .replace(/\[\.\.\.(\w+)\]/g, '(.+)')
        .replace(/\[(\w+)\]/g, '([^/]+)');
      const regex = new RegExp(`^${pattern}$`);
      if (regex.test(pathname)) {
        return pathname;
      }
    }
  }

  // Distinguish between legitimate 404s and bot traffic
  if (isBotPattern(pathname)) {
    return '/bot-scan';
  }
  return '/unknown';
}

app.prepare().then(() => {
  // Load routes after Next.js is ready
  KNOWN_ROUTES_SET = loadKnownRoutes();

  // Metrics endpoint on sidecar port
  createServer(async (req, res) => {
    if (req.url === '/metrics') {
      res.setHeader('Content-Type', register.contentType);
      res.end(await register.metrics());
    } else {
      res.statusCode = 404;
      res.end('Not found');
    }
  }).listen(9090, () => {
    console.log('📡 Prometheus metrics on port 9090');
  });

  // Main Next.js server
  createServer((req: IncomingMessage, res: ServerResponse) => {
    const start = Date.now();
    const method = req.method || 'GET';
    const parsedUrl = parse(req.url || '/', true);
    const route = parsedUrl.pathname || '/';

    // Skip internal Next.js routes and static files
    if (IGNORED_PREFIXES.some(prefix => route.startsWith(prefix))) {
      handle(req, res, parsedUrl);
      return;
    }

    // Skip image files only
    // const isImage = /\.(jpg|jpeg|png|gif|svg|webp|ico)$/i.test(route);
    // if (isImage) {
    // handle(req, res, parsedUrl);
    // return;
    // }

    // ✅ Normalize the route: known routes stay as-is, unknown → '/unknown'
    const normalizedRoute = normalizeRoute(route);

    httpActiveRequests.labels(method).inc();

    // Patch res.end — by the time Next.js calls this,
    // res.statusCode is already the real value (200, 404, 500 etc.)
    const originalEnd = res.end.bind(res);
    (res as any).end = function (...args: any[]) {
      const status = res.statusCode.toString();
      const duration = (Date.now() - start) / 1000;

      httpRequestDuration.labels(method, normalizedRoute, status).observe(duration);
      httpRequestTotal.labels(method, normalizedRoute, status).inc();
      httpActiveRequests.labels(method).dec();

      // ✅ Log suspicious bot traffic for analysis
      if (normalizedRoute === '/bot-scan') {
        console.log(JSON.stringify({
          timestamp: new Date().toISOString(),
          type: 'bot_scan',
          method,
          path: route, // Original path, not normalized
          status,
          ip: req.headers['x-forwarded-for'] || req.socket.remoteAddress,
          userAgent: req.headers['user-agent'],
        }));
      }
      return originalEnd(...args);
    };
    handle(req, res, parsedUrl);
  }).listen(3000, () => {
    console.log('🚀 Next.js server on port 3000');
  });
}); 