apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-website-deployment
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-website
  # can add strategy here when base kubernetes works
  template:
    metadata:
      name: nextjs-website-pod
      labels: 
        app: nextjs-website
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule # Force 1 on each node
          labelSelector:
            matchLabels:
              app: nextjs-website
      containers:
      - name: nextjs-website-container
        image: daviancold/my-portfolio-website-arm:latest
        ports:
        - name: http
          containerPort: 3000
        - name: metrics
          containerPort: 9090
        resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"    # Burst to 1 full oCPU for fast page loads
              memory: "1Gi"