apiVersion: v1
kind: Service
metadata:
  name: nextjs-website-service
  namespace: apps
  labels:
    app: nextjs-website
spec:
  type: ClusterIP
  selector:
    app: nextjs-website
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics