apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nextjs-metrics
  namespace: apps
  labels:
    release: prometheus-stack  # must match your Helm release name
spec:
  namespaceSelector:
    matchNames:
      - apps
  selector:
    matchLabels:
      app: nextjs-website  # must match your Service labels
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s