apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/subnet: "ocid1.subnet.oc1.ap-singapore-1.aaaaaaaa76gaj6pjjokstxsl2nqe2jzgplsj23vvsugtkc2jcbecb2uv2z5q"
    oci.oraclecloud.com/reserved-ips: "161.118.249.70"
