# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: grafana
#   namespace: argocd
# spec:
#   project: otel-demo
#   source:
#     repoURL: https://grafana.github.io/helm-charts
#     chart: grafana
#     targetRevision: "*"
#     helm:
#       valueFiles:
#         - ../values/grafana-values.yml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: grafanalabs
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true