# k8s/argocd/namespaces-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs-website
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: image=daviancold/my-portfolio-website-arm:latest
    argocd-image-updater.argoproj.io/image.update-strategy: digest
    argocd-image-updater.argoproj.io/image.platform: linux/arm64
    argocd-image-updater.argoproj.io/image.pull-secret: pullsecret:argocd/dockerhub-credentials
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/daviancold/PortfolioWebsite2.git'
    path: k8s/apps/nextjs
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true